export const EmailContentMode = {
  NONE: "NONE",
  METADATA_ONLY: "METADATA_ONLY",
  PLAIN_TEXT_PREFERRED: "PLAIN_TEXT_PREFERRED",
  HTML_ALLOWED: "HTML_ALLOWED",
  RAW: "RAW",
} as const;

export type EmailContentMode = (typeof EmailContentMode)[keyof typeof EmailContentMode];

export const EmailParseStatus = {
  PENDING: "PENDING",
  COMPLETED: "COMPLETED",
  FAILED: "FAILED",
} as const;

export type EmailParseStatus = (typeof EmailParseStatus)[keyof typeof EmailParseStatus];

export const EmailParseSource = {
  SCHEDULER: "SCHEDULER",
  MANUAL: "MANUAL",
} as const;

export type EmailParseSource = (typeof EmailParseSource)[keyof typeof EmailParseSource];

export interface SearchEmailsRequest {
  unreadOnly?: boolean;
  includeSpamTrash?: boolean;
  labelIds?: string[];
  query?: string;
  from?: string;
  subject?: string;
  after?: string;
  before?: string;
  maxResults?: number;
  pageToken?: string | null;
  contentMode?: EmailContentMode;
  includeAttachments?: boolean;
  includeAttachmentContent?: boolean;
}

export interface EmailAttachmentMetadataResponse {
  /** Stable MIME part identifier within the message ("1", "0.1", …) — use this to address attachments. */
  partId: string;
  /** Regenerated by Gmail on every fetch — never persist or reuse across requests. */
  attachmentId: string;
  filename: string;
  mimeType: string;
  sizeBytes: number | null;
  inline: boolean;
  skipped: boolean;
  skipReason: string | null;
}

export interface EmailMessageResponse {
  providerMessageId: string;
  threadId: string;
  historyId: string;
  internalDate: number | null;
  labelIds: string[] | null;
  from: string | null;
  to: string | null;
  cc: string | null;
  subject: string | null;
  dateHeader: string | null;
  snippet: string | null;
  contentType: string | null;
  content: string | null;
  contentTruncated: boolean;
  attachments: EmailAttachmentMetadataResponse[] | null;
}

export interface EmailSearchResponse {
  messages: EmailMessageResponse[];
  nextPageToken: string | null;
  resultSizeEstimate: number | null;
}

export interface ParseEmailRequest {
  systemPrompt?: string;
  expectedJsonSchema?: Record<string, unknown>;
  /** Model override; must be one of the configured allowed models. Omitted = server default. */
  aiModel?: string;
}

export interface AiModelsResponse {
  /** Models allowed as a per-parse override; empty means overrides are disabled. */
  models: string[];
  /** Model used when no override is requested; null when the provider default applies. */
  defaultModel: string | null;
}

/** Optional parse-history filters — all omitted means the full history for the connector. */
export interface ParseHistoryFilters {
  status?: EmailParseStatus;
  source?: EmailParseSource;
  /** Exact match — used by the "only selected email" mode. */
  providerMessageId?: string;
  /** Case-insensitive contains. */
  emailFrom?: string;
  /** Case-insensitive contains. */
  emailSubject?: string;
  /** ISO-8601 date-time. */
  createdAfter?: string;
  createdBefore?: string;
}

export interface EmailParseResultResponse {
  uuid: string;
  providerMessageId: string;
  subject: string | null;
  from: string | null;
  status: EmailParseStatus;
  source: EmailParseSource;
  purpose: string | null;
  systemPrompt: string | null;
  expectedJsonSchema: Record<string, unknown> | null;
  aiProvider: string | null;
  aiModel: string | null;
  resultJson: Record<string, unknown> | null;
  resultText: string | null;
  errorMessage: string | null;
  attachmentsProcessed: number | null;
  attachmentsSkipped: number | null;
  requestedByUserUuid: string | null;
  createdAt: string;
  completedAt: string | null;
}

export interface EmailParseResultPageResponse {
  results: EmailParseResultResponse[];
  page: number;
  size: number;
  totalElements: number;
}
